DISTANCE_VIOLATION = "Farms within 200 meters of each other"
DRY_WEIGHT_VIOLATION = "Dry weight exceeds corresponding wet weight"
DRY_WEIGHT_OUTLIER_VIOLATION = "Dry weight is outside the standard deviation of other data points"
SIMILAR_PHOTOS_VIOLATION = "Duplicate photos"
MULTIPLE_MEASUREMENTS_VIOLATION = "Multiple measurements from same farm and crop"
